services:
  - type: web
    name: maxibox
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GCP_SA_KEY_JSON
        sync: false
      - key: GCP_PROJECT_ID
        value: prj-six-aa2bbe69
      - key: GCP_REGION
        value: us-east5
